#ifndef TIMER_H
#define TIMER_H

#include "mode_fsm.h"
#include "argb.h"
#include "input_manager.h"
#include "spi.h"

#ifdef __cplusplus
extern "C" {
#endif

#define TIMER_LED_COUNT 47

typedef uint8_t Timer_Glyph;

#define TIMER_SEGMENT_A (1u << 0)
#define TIMER_SEGMENT_B (1u << 1)
#define TIMER_SEGMENT_C (1u << 2)
#define TIMER_SEGMENT_D (1u << 3)
#define TIMER_SEGMENT_E (1u << 4)
#define TIMER_SEGMENT_F (1u << 5)
#define TIMER_SEGMENT_G (1u << 6)

#define TIMER_DIGIT_BLANK 0
#define TIMER_DIGIT_0 (TIMER_SEGMENT_A | TIMER_SEGMENT_B | TIMER_SEGMENT_C | TIMER_SEGMENT_D | \
                       TIMER_SEGMENT_E | TIMER_SEGMENT_F)
#define TIMER_DIGIT_1 (TIMER_SEGMENT_B | TIMER_SEGMENT_C)
#define TIMER_DIGIT_2 (TIMER_SEGMENT_A | TIMER_SEGMENT_B | TIMER_SEGMENT_D | TIMER_SEGMENT_E | TIMER_SEGMENT_G)
#define TIMER_DIGIT_3 (TIMER_SEGMENT_A | TIMER_SEGMENT_B | TIMER_SEGMENT_C | TIMER_SEGMENT_D | TIMER_SEGMENT_G)
#define TIMER_DIGIT_4 (TIMER_SEGMENT_B | TIMER_SEGMENT_C | TIMER_SEGMENT_F | TIMER_SEGMENT_G)
#define TIMER_DIGIT_5 (TIMER_SEGMENT_A | TIMER_SEGMENT_C | TIMER_SEGMENT_D | TIMER_SEGMENT_F | TIMER_SEGMENT_G)
#define TIMER_DIGIT_6 (TIMER_SEGMENT_A | TIMER_SEGMENT_C | TIMER_SEGMENT_D | TIMER_SEGMENT_E | \
                       TIMER_SEGMENT_F | TIMER_SEGMENT_G)
#define TIMER_DIGIT_7 (TIMER_SEGMENT_A | TIMER_SEGMENT_B | TIMER_SEGMENT_C)
#define TIMER_DIGIT_8 (TIMER_SEGMENT_A | TIMER_SEGMENT_B | TIMER_SEGMENT_C | TIMER_SEGMENT_D | \
                       TIMER_SEGMENT_E | TIMER_SEGMENT_F | TIMER_SEGMENT_G)
#define TIMER_DIGIT_9 (TIMER_SEGMENT_A | TIMER_SEGMENT_B | TIMER_SEGMENT_C | TIMER_SEGMENT_D | \
                       TIMER_SEGMENT_F | TIMER_SEGMENT_G)
#define TIMER_DIGIT_DASH TIMER_SEGMENT_G

#define STRIKES_SEGMENT_A1 (1u << 0)
#define STRIKES_SEGMENT_A2 (1u << 1)
#define STRIKES_SEGMENT_K  (1u << 2)
#define STRIKES_SEGMENT_B  (1u << 3)
#define STRIKES_SEGMENT_G2 (1u << 4)
#define STRIKES_SEGMENT_L  (1u << 5)
#define STRIKES_SEGMENT_C  (1u << 6)
#define STRIKES_SEGMENT_D2 (1u << 7)
#define STRIKES_SEGMENT_D1 (1u << 8)
#define STRIKES_SEGMENT_E  (1u << 9)
#define STRIKES_SEGMENT_N  (1u << 10)
#define STRIKES_SEGMENT_M  (1u << 11)
#define STRIKES_SEGMENT_G1 (1u << 12)
#define STRIKES_SEGMENT_F  (1u << 13)
#define STRIKES_SEGMENT_H  (1u << 14)
#define STRIKES_SEGMENT_J  (1u << 15)

#define STRIKES_DIGIT_BLANK 0

#define STRIKES_DIGIT_0 (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_B  | STRIKES_SEGMENT_C  | \
                 STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2 | STRIKES_SEGMENT_E  | STRIKES_SEGMENT_F)
#define STRIKES_DIGIT_1 (STRIKES_SEGMENT_B  | STRIKES_SEGMENT_C)
#define STRIKES_DIGIT_2 (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_B  | STRIKES_SEGMENT_G1 | \
                 STRIKES_SEGMENT_G2 | STRIKES_SEGMENT_E  | STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2)
#define STRIKES_DIGIT_3 (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_B  | STRIKES_SEGMENT_C  | \
                 STRIKES_SEGMENT_G1 | STRIKES_SEGMENT_G2 | STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2)
#define STRIKES_DIGIT_4 (STRIKES_SEGMENT_F  | STRIKES_SEGMENT_G1 | STRIKES_SEGMENT_G2 | STRIKES_SEGMENT_B | \
                 STRIKES_SEGMENT_C)
#define STRIKES_DIGIT_5 (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_F  | STRIKES_SEGMENT_G1 | \
                 STRIKES_SEGMENT_G2 | STRIKES_SEGMENT_C  | STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2)
#define STRIKES_DIGIT_6 (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_F  | STRIKES_SEGMENT_E  | \
                 STRIKES_SEGMENT_G1 | STRIKES_SEGMENT_G2 | STRIKES_SEGMENT_C  | STRIKES_SEGMENT_D1 | \
                 STRIKES_SEGMENT_D2)
#define STRIKES_DIGIT_7 (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_B | STRIKES_SEGMENT_C)
#define STRIKES_DIGIT_8 (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_B  | STRIKES_SEGMENT_C  | \
                 STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2 | STRIKES_SEGMENT_E  | STRIKES_SEGMENT_F  | \
                 STRIKES_SEGMENT_G1 | STRIKES_SEGMENT_G2)
#define STRIKES_DIGIT_9 (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_B  | STRIKES_SEGMENT_C  | \
                 STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2 | STRIKES_SEGMENT_F  | STRIKES_SEGMENT_G1 | \
                 STRIKES_SEGMENT_G2)

#define STRIKES_DIGIT_A (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_B  | STRIKES_SEGMENT_C | \
                 STRIKES_SEGMENT_E  | STRIKES_SEGMENT_F  | STRIKES_SEGMENT_G1 | STRIKES_SEGMENT_G2)
#define STRIKES_DIGIT_B (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_B  | STRIKES_SEGMENT_C | \
                 STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2 | STRIKES_SEGMENT_G2 | STRIKES_SEGMENT_J | \
                 STRIKES_SEGMENT_M)
#define STRIKES_DIGIT_C (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2 | \
                 STRIKES_SEGMENT_E  | STRIKES_SEGMENT_F)
#define STRIKES_DIGIT_D (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_B  | STRIKES_SEGMENT_C | \
                 STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2 | STRIKES_SEGMENT_J  | STRIKES_SEGMENT_M)
#define STRIKES_DIGIT_E (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2 | \
                 STRIKES_SEGMENT_E  | STRIKES_SEGMENT_F  | STRIKES_SEGMENT_G1)
#define STRIKES_DIGIT_F (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_E  | STRIKES_SEGMENT_F | \
                 STRIKES_SEGMENT_G1)
#define STRIKES_DIGIT_G (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_C  | STRIKES_SEGMENT_D1 | \
                 STRIKES_SEGMENT_D2 | STRIKES_SEGMENT_E  | STRIKES_SEGMENT_F  | STRIKES_SEGMENT_G2)
#define STRIKES_DIGIT_H (STRIKES_SEGMENT_B  | STRIKES_SEGMENT_C  | STRIKES_SEGMENT_E  | STRIKES_SEGMENT_F | \
                 STRIKES_SEGMENT_G1 | STRIKES_SEGMENT_G2)
#define STRIKES_DIGIT_I (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2 | \
                 STRIKES_SEGMENT_J  | STRIKES_SEGMENT_M)
#define STRIKES_DIGIT_J (STRIKES_SEGMENT_B | STRIKES_SEGMENT_C | STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2)
#define STRIKES_DIGIT_K (STRIKES_SEGMENT_E | STRIKES_SEGMENT_F | STRIKES_SEGMENT_G1 | STRIKES_SEGMENT_K | \
                 STRIKES_SEGMENT_L)
#define STRIKES_DIGIT_L (STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2 | STRIKES_SEGMENT_E | STRIKES_SEGMENT_F)
#define STRIKES_DIGIT_M (STRIKES_SEGMENT_B | STRIKES_SEGMENT_C | STRIKES_SEGMENT_E | STRIKES_SEGMENT_F | \
                 STRIKES_SEGMENT_H | STRIKES_SEGMENT_K)
#define STRIKES_DIGIT_N (STRIKES_SEGMENT_B | STRIKES_SEGMENT_C | STRIKES_SEGMENT_E | STRIKES_SEGMENT_F | \
                 STRIKES_SEGMENT_H | STRIKES_SEGMENT_L)
#define STRIKES_DIGIT_O (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_B  | STRIKES_SEGMENT_C | \
                 STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2 | STRIKES_SEGMENT_E  | STRIKES_SEGMENT_F)
#define STRIKES_DIGIT_P (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_B  | STRIKES_SEGMENT_E | \
                 STRIKES_SEGMENT_F  | STRIKES_SEGMENT_G1 | STRIKES_SEGMENT_G2)
#define STRIKES_DIGIT_Q (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_B  | STRIKES_SEGMENT_C | \
                 STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2 | STRIKES_SEGMENT_E  | STRIKES_SEGMENT_F | \
                 STRIKES_SEGMENT_L)
#define STRIKES_DIGIT_R (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_B  | STRIKES_SEGMENT_E | \
                 STRIKES_SEGMENT_F  | STRIKES_SEGMENT_G1 | STRIKES_SEGMENT_G2 | STRIKES_SEGMENT_L)
#define STRIKES_DIGIT_S (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_C  | STRIKES_SEGMENT_D1 | \
                 STRIKES_SEGMENT_D2 | STRIKES_SEGMENT_F  | STRIKES_SEGMENT_G1 | STRIKES_SEGMENT_G2)
#define STRIKES_DIGIT_T (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_J | STRIKES_SEGMENT_M)
#define STRIKES_DIGIT_U (STRIKES_SEGMENT_B  | STRIKES_SEGMENT_C  | STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2 | \
                 STRIKES_SEGMENT_E  | STRIKES_SEGMENT_F)
#define STRIKES_DIGIT_V (STRIKES_SEGMENT_E | STRIKES_SEGMENT_F | STRIKES_SEGMENT_K | STRIKES_SEGMENT_N)
#define STRIKES_DIGIT_W (STRIKES_SEGMENT_B | STRIKES_SEGMENT_C | STRIKES_SEGMENT_E | STRIKES_SEGMENT_F | \
                 STRIKES_SEGMENT_L | STRIKES_SEGMENT_N)
#define STRIKES_DIGIT_X (STRIKES_SEGMENT_H | STRIKES_SEGMENT_K | STRIKES_SEGMENT_L | STRIKES_SEGMENT_N)
#define STRIKES_DIGIT_Y (STRIKES_SEGMENT_H | STRIKES_SEGMENT_K | STRIKES_SEGMENT_M)
#define STRIKES_DIGIT_Z (STRIKES_SEGMENT_A1 | STRIKES_SEGMENT_A2 | STRIKES_SEGMENT_D1 | STRIKES_SEGMENT_D2 | \
                 STRIKES_SEGMENT_K  | STRIKES_SEGMENT_N)

#define STRIKES_DIGIT_DASH (STRIKES_SEGMENT_G1 | STRIKES_SEGMENT_G2)
#define STRIKES_DIGIT_ASTERISK (STRIKES_SEGMENT_H | STRIKES_SEGMENT_J | STRIKES_SEGMENT_K | \
                        STRIKES_SEGMENT_L | STRIKES_SEGMENT_M | STRIKES_SEGMENT_N)

typedef struct {
    ARGB_Strip strip;
    ARGB_LED leds[TIMER_LED_COUNT];
    ARGB_LED display_colour;
    uint32_t startup_next_step_ms;
    uint8_t startup_step;

    uint32_t attract_next_tick_ms;
    uint16_t attract_remaining_centiseconds;
    uint32_t attract_strikes_next_event_ms;
    uint32_t attract_strikes_next_flash_ms;
    uint8_t attract_strikes_state;
    bool attract_strikes_visible;

    IM_EventQueue input_queue;

    IM_RotaryEncoderState rotary_state;
    IM_RotaryEncoderConfig rotary_config;
    IM_DigitalChannelState rotary_button_channel_state[1];
    IM_DigitalInputState rotary_button_state;
    IM_DigitalInputConfig rotary_button_config;
    IM_Handle rotary_button_handle;

    uint32_t strikes_data;
    SPI_Transaction strikes_transaction;
} Timer_Data;

extern Mode_Definition timer_mode;

#ifdef __cplusplus
}
#endif

#endif //TIMER_H
