M48
; DRILL file KiCad 10.0.3 date 2026-06-27T21:23:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-27T21:23:20+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X44.71Y-65.484
X44.71Y-67.516
X49.79Y-66.5
T2
X23.5Y-23.49
X23.5Y-66.49
X66.5Y-23.49
X66.5Y-66.49
M30
