#ifndef CONFIG_H
#define CONFIG_H

#include <hal/nvm.h>
#include <stdint.h>

#define CONFIG_LOC_VERSION CONFIG_LOC_VERSION_LOW
#define CONFIG_LOC_VERSION_LOW (NVM_EEPROM_APPLICATION_BASE + 0x00)
#define CONFIG_LOC_VERSION_HIGH (NVM_EEPROM_APPLICATION_BASE + 0x01)
#define CONFIG_LOC_MODE (NVM_EEPROM_APPLICATION_BASE + 0x02)

void config_init(void);

#endif