M48
; DRILL file {KiCad 9.0.6} date 2026-02-24T21:10:48+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-24T21:10:48+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X42.234Y-39.96
X43.25Y-45.04
X44.266Y-39.96
T2
X23.5Y-51.5
X33.0Y-32.5
X68.0Y-32.5
X77.5Y-51.5
M30
