M48
; DRILL file KiCad 10.0.3 date 2026-06-27T21:18:16
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-27T21:18:16+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X37.46Y-84.5
X42.54Y-83.484
X42.54Y-85.516
T2
X24.0Y-24.0
X24.0Y-116.0
X56.0Y-24.0
X56.0Y-116.0
M30
