package process

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Quote bytes, not Go runes: fixed-width octal escapes are valid portable C
// and cannot consume following digits. UTF-8 names retain their original bytes.
func cString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, c := range []byte(s) {
		if c >= 32 && c < 127 && c != '"' && c != '\\' && c != '?' {
			b.WriteByte(c)
		} else {
			fmt.Fprintf(&b, "\\%03o", c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func everyMinutes(f frequency) uint32 {
	if f.Source != frequencyJourneys && f.Source != frequencyPeriod {
		return 0
	}
	// Average any range and round to the nearest whole minute, at least one.
	return uint32(max(1, (uint64(f.MinSeconds)+uint64(f.MaxSeconds)+60)/120))
}

func renderHeader(d *dataset) []byte {
	var b bytes.Buffer
	b.WriteString(`/* Generated by tool module underground process. Source: https://api.tfl.gov.uk/
 * IDs are array indices and may change when regenerated.
 * Route stops retain all stations between the first and last zone 1/2 stop,
 * plus one outside stop at each end. Origin/destination are actual termini.
 * Station route indexes refer only to retained sequences, including boundaries.
 * A route may visit a station more than once; its reverse index lists it once.
 * Include in one translation unit to avoid duplicating the static tables.
 */
#ifndef KTANE_UNDERGROUND_DATA_H
#define KTANE_UNDERGROUND_DATA_H
#include <stdint.h>

typedef uint16_t UndergroundStationID;
typedef uint16_t UndergroundLineID;
typedef uint16_t UndergroundRouteID;
#define UNDERGROUND_NO_STATION ((UndergroundStationID)UINT16_MAX)
#define UNDERGROUND_NO_VIA_STOP_INDEX UINT8_MAX
typedef struct { const char *name; } UndergroundLine;
typedef struct {
    const char *name;
    uint8_t in_zone;
    uint16_t routes_offset;
    uint8_t routes_count;
} UndergroundStation;
typedef struct {
    UndergroundLineID line;
    UndergroundStationID origin, destination;
    uint16_t stops_offset;
    uint8_t stops_count;
    uint8_t every_minutes;
    UndergroundStationID via;
    uint8_t via_stop_index;
} UndergroundRoute;

`)
	fmt.Fprintf(&b, "#define UNDERGROUND_LINE_COUNT %dU\n#define UNDERGROUND_STATION_COUNT %dU\n#define UNDERGROUND_ROUTE_COUNT %dU\n\n", len(d.Lines), len(d.Stations), len(d.Routes))
	b.WriteString("static const UndergroundLine underground_lines[] = {\n")
	for _, l := range d.Lines {
		fmt.Fprintf(&b, "    {.name = %s},\n", cString(l.Name))
	}
	b.WriteString("};\n\n")
	b.WriteString("static const UndergroundStationID underground_route_stops[] = {\n")
	for _, r := range d.Routes {
		b.WriteString("    ")
		for _, id := range r.Stops {
			fmt.Fprintf(&b, "%d, ", id)
		}
		b.WriteByte('\n')
	}
	b.WriteString("};\n\n")
	b.WriteString("static const UndergroundRoute underground_routes[] = {\n")
	offset := 0
	for _, r := range d.Routes {
		via, viaStopIndex := noStation, noViaStopIndex
		if r.HasVia {
			via, viaStopIndex = r.Via, r.ViaStopIndex
		}
		fmt.Fprintf(&b, "    {.line = %d, .origin = %d, .destination = %d, .stops_offset = %dU, .stops_count = %dU, .every_minutes = %dU, .via = %dU, .via_stop_index = %dU},\n", r.Line, r.Origin, r.Destination, offset, len(r.Stops), everyMinutes(r.Frequency), via, viaStopIndex)
		offset += len(r.Stops)
	}
	b.WriteString("};\n\n")
	b.WriteString("static const UndergroundRouteID underground_station_routes[] = {\n")
	for _, s := range d.Stations {
		if len(s.Routes) == 0 {
			continue
		}
		b.WriteString("    ")
		for _, id := range s.Routes {
			fmt.Fprintf(&b, "%d, ", id)
		}
		b.WriteByte('\n')
	}
	b.WriteString("};\n\n")
	b.WriteString("static const UndergroundStation underground_stations[] = {\n")
	offset = 0
	for _, s := range d.Stations {
		flag := 0
		if s.InZone {
			flag = 1
		}
		fmt.Fprintf(&b, "    {.name = %s, .in_zone = %d, .routes_offset = %dU, .routes_count = %dU},\n", cString(s.Name), flag, offset, len(s.Routes))
		offset += len(s.Routes)
	}
	b.WriteString("};\n\n#endif /* KTANE_UNDERGROUND_DATA_H */\n")
	return b.Bytes()
}
func writeHeader(path string, d *dataset) error {
	if path == "" {
		return fmt.Errorf("--output is required")
	}
	f, err := os.CreateTemp(filepath.Dir(path), ".underground-*.h")
	if err != nil {
		return err
	}
	defer os.Remove(f.Name())
	if _, err = f.Write(renderHeader(d)); err != nil {
		f.Close()
		return err
	}
	if err = f.Chmod(0644); err != nil {
		f.Close()
		return err
	}
	if err = f.Close(); err != nil {
		return err
	}
	return os.Rename(f.Name(), path)
}
