M48
; DRILL file {KiCad 9.0.6} date 2026-02-24T16:19:38+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-24T16:19:38+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X37.46Y-83.484
X37.46Y-85.516
X42.54Y-84.5
T2
X24.0Y-24.0
X24.0Y-116.0
X56.0Y-24.0
X56.0Y-116.0
M30
