M48
; DRILL file {KiCad 9.0.6} date 2026-02-24T20:37:53+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-24T20:37:53+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X67.335Y-46.15
X72.415Y-45.134
X72.415Y-47.166
T2
X43.0Y-29.5
X43.0Y-71.5
X115.0Y-29.5
X115.0Y-71.5
M30
