#ifndef GPIO_H
#define GPIO_H

#include "stm32g0xx_hal.h"

#define REAR_EFUSE_FLT_Pin GPIO_PIN_9
#define REAR_EFUSE_FLT_GPIO_Port GPIOB
#define REAR_EFUSE_EN_Pin GPIO_PIN_14
#define REAR_EFUSE_EN_GPIO_Port GPIOC
#define REAR_MODULE_DETECT_Pin GPIO_PIN_15
#define REAR_MODULE_DETECT_GPIO_Port GPIOC

#define REAR_UART_TX_Pin GPIO_PIN_0
#define REAR_UART_TX_GPIO_Port GPIOA
#define REAR_UART_RX_Pin GPIO_PIN_1
#define REAR_UART_RX_GPIO_Port GPIOA

#define REAR_BOOT_Pin GPIO_PIN_2
#define REAR_BOOT_GPIO_Port GPIOA
#define REAR_ILM_Pin GPIO_PIN_3
#define REAR_ILM_GPIO_Port GPIOA

#define BUTTON_Pin GPIO_PIN_4
#define BUTTON_GPIO_Port GPIOA

#define BUS_TX_Pin GPIO_PIN_5
#define BUS_TX_GPIO_Port GPIOA
#define BUS_RX_Pin GPIO_PIN_0
#define BUS_RX_GPIO_Port GPIOB
#define BUS_DE_Pin GPIO_PIN_1
#define BUS_DE_GPIO_Port GPIOB

#define STATUS_LED_Pin GPIO_PIN_6
#define STATUS_LED_GPIO_Port GPIOA

#define FRONT_ILM_Pin GPIO_PIN_2
#define FRONT_ILM_GPIO_Port GPIOB
#define FRONT_MODULE_DETECT_Pin GPIO_PIN_8
#define FRONT_MODULE_DETECT_GPIO_Port GPIOA

#define FRONT_UART_TX_Pin GPIO_PIN_9
#define FRONT_UART_TX_GPIO_Port GPIOA
#define FRONT_UART_RX_Pin GPIO_PIN_10
#define FRONT_UART_RX_GPIO_Port GPIOA

#define FRONT_BOOT_Pin GPIO_PIN_6
#define FRONT_BOOT_GPIO_Port GPIOC
#define FRONT_EFUSE_FLT_Pin GPIO_PIN_11
#define FRONT_EFUSE_FLT_GPIO_Port GPIOA
#define FRONT_EFUSE_EN_Pin GPIO_PIN_12
#define FRONT_EFUSE_EN_GPIO_Port GPIOA

#endif // GPIO_H
